default_config:

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize/customize.yaml

frontend:
  themes: !include themes.yaml

logger:
  default: warn
  logs:
    homeassistant.components.http.ban: warning

recorder:
  db_url: !secret db_connection_string
  purge_keep_days: 30
  commit_interval: 10


http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret local_ip
    - 127.0.0.1
    - ::1
    - 172.16.0.0/12

sensor:
  - platform: fail2ban
    jails:
      - hass-iptables
    file_path: /fail2ban/fail2ban.log

automation: !include automations.yaml
