version: '3.6'

networks:
  home:
    attachable: true
    name: home
  db:

services:
  hass:
    image: homeassistant/home-assistant
    container_name: hass
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - type: bind
        source: ./conf/hass
        target: /config
      - type: bind
        source: ./conf/swag/log/fail2ban
        target: /fail2ban
    ports:
      - 8123:8123
    depends_on:
      - swag
      - mariadb
    networks:
      - home
      - db

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - type: bind
        source: ./z2bdata
        target: /app/data
      - type: bind
        source: /run/udev
        target: /run/udev
        read_only: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - home

  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=home.arendt-stein.de
      - SUBDOMAINS=cloud,hass
      - VALIDATION=http
      - EMAIL=pascal.stein@gmail.com
    #  - STAGING=true #optional
    volumes:
      - ./conf/swag:/config
      - ./conf/hass:/hass
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - home

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./conf/heimdall:/config
    restart: unless-stopped
    depends_on:
      - swag
    networks:
      - home

  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_DATABASE=homeassistant
      - MYSQL_USER=hass
    volumes:
      - ./data/mysql:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - db

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./conf/nextcloud:/config
      - ./data/nextcloud:/data
    restart: unless-stopped
    depends_on:
      - swag
      - mariadb
    networks:
      - home
      - db

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "10.10.0.4:53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      #uncomment this to use over WiFi
      # INTERFACE: 'wlan0'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      # Alternatively, run docker-compose exec pihole sudo pihole -a -p after
      # the container is up to change the password
    volumes:
      - './conf/pihole/:/etc/pihole/'
      - './conf/dnsmasq/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    # The first entry must be 127.0.0.1, otherwise startup will fail as the
    # pihole will try to query itself over network before being available
    dns:
      - 127.0.0.1
      - 8.8.8.8
    restart: unless-stopped
