version: '3.8'

services:
  hass:
    image: homeassistant/home-assistant
    hostname: homeassistant
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    network_mode: host
    volumes:
      - type: bind
        source: ./ha_conf
        target: /config
    depends_on:
      - mariadb

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    network_mode: host
    restart: unless-stopped

  mariadb:
    hostname: mariadb
    image: mariadb
    restart: unless-stopped
    network_mode: host
    volumes:
      - type: bind
        source: /var/lib/mariadb_docker
        target: /var/lib/mysql