version: '3.6'

services:
  hass:
    image: homeassistant/home-assistant
    hostname: homeassistant
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    network_mode: host
    volumes:
      - type: bind
        source: ./ha_conf
        target: /config
    # depends_on:
      # - mariadb

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    network_mode: host
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - type: bind
        source: ./z2bdata
        target: /app/data
      - type: bind
        source: /run/udev
        target: /run/udev
        read_only: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Amsterdam

  # mariadb:
  #   hostname: mariadb
  #   image: ${DB_IMAGE_NAME}
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
  #     MYSQL_DATABASE: hassdb
  #     MYSQL_USER: hass
  #     MYSQL_PASSWORD: ${DB_USER_PASSWD}
  #   volumes:
  #     - type: bind
  #       source: ./db_data
  #       target: /var/lib/mysql