version: '3.6'

services:
  hass:
    image: homeassistant/home-assistant
    container_name: hass
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - type: bind
        source: ./ha_conf
        target: /config
      - type: bind
        source: ./proxyconfig/log/fail2ban
        target: /fail2ban
    ports:
      - 8123:8123
    # depends_on:
      # - mariadb

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - type: bind
        source: ./z2bdata
        target: /app/data
      - type: bind
        source: /run/udev
        target: /run/udev
        read_only: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Amsterdam

  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=home.pascalstein.de
      - SUBDOMAINS=hass
      - VALIDATION=http
      - EMAIL=pascal.stein@gmail.com
      #- STAGING=true #optional
    volumes:
      - ./proxyconfig:/config
      - ./ha_conf:/hass
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./heimdall_conf:/config
    restart: unless-stopped

  # mariadb:
  #   hostname: mariadb
  #   image: ${DB_IMAGE_NAME}
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
  #     MYSQL_DATABASE: hassdb
  #     MYSQL_USER: hass
  #     MYSQL_PASSWORD: ${DB_USER_PASSWD}
  #   volumes:
  #     - type: bind
  #       source: ./db_data
  #       target: /var/lib/mysql
