version: '3.6'

services:
  pihole:
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      #uncomment this to use over WiFi
      # INTERFACE: 'wlan0'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      # Alternatively, run docker-compose exec pihole sudo pihole -a -p after
      # the container is up to change the password
    volumes:
      - './pihole/:/etc/pihole/'
      - './dnsmasq/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    # The first entry must be 127.0.0.1, otherwise startup will fail as the
    # pihole will try to query itself over network before being available
    dns:
      - 127.0.0.1
      - 8.8.8.8
    restart: unless-stopped