homeassistant: true
# MQTT settings
mqtt:
  # MQTT base topic for Zigbee2MQTT MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://mosquitto'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password
  advanced:
  #  network_key: GENERATE
    log_level: debug