default_config:

mqtt:
  discovery: true
  broker: localhost
  port: 1883
# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize/customize.yaml

hacs:
  token: !secret hacs_github_token
  sidepanel_title: HACS
  sidepanel_icon: mdi:store
  options:
    experimental: true

lovelace:
  mode: yaml

frontend:
  themes: !include themes.yaml

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
