default_config:

tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize/customize.yaml

frontend:
  themes: !include themes.yaml

logger:
  default: warn
  logs:
    homeassistant.components.http.ban: warning

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.10.0.2
    - 127.0.0.1

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sensor:
  - platform: fail2ban
    jails:
      - hass-iptables
    file_path: /fail2ban/fail2ban.log

automation: !include automations.yaml
